---
name: Build and Release binary

on:
  release:
    types:
      - published

jobs:
  build-on-other:
    runs-on: ubuntu-18.04
    name: Build release binary on ${{ matrix.arch }} ${{ matrix.distro }}

    strategy:
      matrix:
        include:
          - arch: armv6
            distro: alpine_latest
          - arch: armv7
            distro: alpine_latest
          - arch: aarch64
            distro: alpine_latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.1

      - name: Build on ${{ matrix.arch }} ${{ matrix.distro }}
        uses: uraimo/run-on-arch-action@v2.1.1
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          env: |
            artifact_name: pifetch-${{ matrix.distro }}_${{ matrix.arch }}
          install: |
            apk add --update make
            apk add --update g++
          run: |
            make build
            cp pifetch /artifacts/${artifact_name}
      - name: Add compiled binary to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'artifacts/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
